version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: prenava-app:latest
    container_name: prenava-app
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - prenava-public-data:/var/www/public
      - prenava-storage-data:/var/www/storage
    networks:
      - prenava-network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: prenava-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - prenava-public-data:/var/www/public
      - prenava-storage-data:/var/www/storage
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - prenava-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: prenava-mysql
    hostname: mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - prenava-mysql-data:/var/lib/mysql
    networks:
      - prenava-network
    command: --collation-server=utf8mb4_unicode_ci --character-set-server=utf8mb4

  redis:
    image: redis:alpine
    container_name: prenava-redis
    restart: unless-stopped
    networks:
      - prenava-network

networks:
  prenava-network:
    driver: bridge

volumes:
  prenava-mysql-data:
  prenava-public-data:
  prenava-storage-data:
